services:
  monbot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PY_VERSION: "3.11"
        APP_UID: 10001
    image: monbot:latest
    container_name: monbot
    restart: unless-stopped
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
      ZABBIX_URL: "${ZABBIX_URL:-http://zabbix-web:8080/}"
      ZABBIX_USER: "${ZABBIX_USER:-api_tg}"
      ZABBIX_PASS: "${ZABBIX_PASS:-change-me}"
      ZABBIX_API_TOKEN: "${ZABBIX_API_TOKEN:-}"
      ZABBIX_VERIFY_SSL: "${ZABBIX_VERIFY_SSL:-true}"
      ZABBIX_TOKEN_MODE: "${ZABBIX_TOKEN_MODE:-auto}"
      SUPPRESS_TLS_WARN: "${SUPPRESS_TLS_WARN:-true}"
      ALLOW_HOSTS: "${ALLOW_HOSTS:-{\"10263\":\"RT\",\"10266\":\"Freez\"}}"
      INITIAL_ADMINS: "${INITIAL_ADMINS:-}"
      IMG_WIDTH: "${IMG_WIDTH:-512}"
      IMG_HEIGHT: "${IMG_HEIGHT:-512}"
      MAINT_LIST_LIMIT: "${MAINT_LIST_LIMIT:-5}"
      DEFAULT_TZ: "${DEFAULT_TZ:-Europe/Moscow}"
      ITEMS_REFRESH_SEC: "${ITEMS_REFRESH_SEC:-3600}"
      # Data/cache locations (override if you prefer different mount points)
      MONBOT_BASE_DIR: "/data"
      MONBOT_CACHE_DIR: "/cache"
      MONBOT_REPORTS_DIR: "/reports"
      MONBOT_DB_PATH: "/data/monbot.db"
      REPORT_META_TTL_SEC: "${REPORT_META_TTL_SEC:-3600}"
      REPORT_WIDGETS_TTL_SEC: "${REPORT_WIDGETS_TTL_SEC:-3600}"
      REPORT_DASHBOARD_ID: "${REPORT_DASHBOARD_ID:-19}"
    volumes:
      - ./data:/data
      - ./cache:/cache
      - ./reports:/reports
